[package]
name = "radio-modulation-visualizer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
cpal = "0.17.1"
eframe = { version = "0.33.3", features = ["wayland"] }
rand = "0.9.2"
thiserror = "2.0.17"
